# Generated by Django 3.1.2 on 2020-11-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='rate',
        ),
        migrations.AddField(
            model_name='gallery',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
